Add CI step to fix ellipsise in strings files

diff --git a/.github/workflows/ci_checks.yml b/.github/workflows/ci_checks.yml
--- a/.github/workflows/ci_checks.yml
+++ b/.github/workflows/ci_checks.yml
@@ -159,6 +159,42 @@ jobs:
       - name: Verify CHANGELOG was updated
         run: current/.github/scripts/verify_file_was_changed.sh master/CHANGELOG.md current/CHANGELOG.md
 
+  fix_strings_ellipsise:
+    runs-on: [ubuntu-latest]
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Fix ellipsise in strings
+        run: .github/scripts/strings_reader.py
+
+      - name: Commit and push
+        run: |
+          #!/usr/bin/env bash
+
+          readonly GIT_HAS_CHANGES=1 # 0 = clean, 1 = dirty
+
+          USER_NAME="${{secrets.USER_NAME}}"
+          USER_EMAIL="${{secrets.USER_EMAIL}}"
+
+          git config user.name "$USER_NAME"
+          git config user.email "$USER_EMAIL"
+
+          # Following git command checks the git diff of staged files
+          # and assigns the exit code to GIT_DIFF_STATUS variable.
+          git diff --quiet; GIT_DIFF_STATUS=$?
+
+          # If the GIT_DIFF_STATUS is 1 (GIT_HAS_CHANGES) then we know
+          # there are changes and we can commit the changes and push
+          # them to new branch
+          if [[ ${GIT_DIFF_STATUS} -eq ${GIT_HAS_CHANGES} ]]; then
+              git add .
+              git commit --amend --no-edit
+              git push -f
+
+              echo 0
+          fi
+
   qa_purge_env:
     runs-on: [ubuntu-latest]
     needs: [qa_lint, qa_unit_tests, mobius_migration_tests, qa_android_tests, qa_build_apk]
